namespace ALittleSecretIngredient
{
    internal enum FileEnum
    {
        God,
        Item,
        Job,
        Person,
        Skill
    }

    internal enum DataSetEnum
    {
        GodGeneral,
        GrowthTable,
        BondLevel,
        Item,
        ItemCategory,
        Alchemy,
        Evolution,
        RefiningMaterialExchange,
        WeaponLevel,
        Compatibility,
        Accessory,
        Gift,
        Reward,
        EngageWeaponEnhancement,
        BattleReward,
        TypeOfSoldier,
        FightingStyle,
        Individual,
        Skill
    }

    internal enum RandomizerDistribution
    {
        Link,
        EngageCount,
        EngageAttackAlly,
        EngageAttackEnemy,
        EngageAttackLink,
        LinkGid,
        EngravePower,
        EngraveWeight,
        EngraveHit,
        EngraveCritical,
        EngraveAvoid,
        EngraveSecure,
        SynchroEnhanceHpAlly,
        SynchroEnhanceStrAlly,
        SynchroEnhanceTechAlly,
        SynchroEnhanceQuickAlly,
        SynchroEnhanceLuckAlly,
        SynchroEnhanceDefAlly,
        SynchroEnhanceMagicAlly,
        SynchroEnhanceMdefAlly,
        SynchroEnhancePhysAlly,
        SynchroEnhanceMoveAlly,
        SynchroEnhanceHpEnemy,
        SynchroEnhanceStrEnemy,
        SynchroEnhanceTechEnemy,
        SynchroEnhanceQuickEnemy,
        SynchroEnhanceLuckEnemy,
        SynchroEnhanceDefEnemy,
        SynchroEnhanceMagicEnemy,
        SynchroEnhanceMdefEnemy,
        SynchroEnhancePhysEnemy,
        SynchroEnhanceMoveEnemy,
        InheritanceSkills,
        SynchroStatSkillsAlly,
        SynchroStatSkillsEnemy,
        SynchroGeneralSkillsAlly,
        SynchroGeneralSkillsEnemy,
        EngageSkills,
        EngageItems,
        Aptitude,
        SkillInheritanceLevel,
        StrongBondLevel,
        DeepSynergyLevel,
        Exp,
        Cost
    }
}
