#pragma warning disable CS8618

namespace ALittleSecretIngredient.Structs
{
    internal class Skill : DataParam
    {
        internal string Out { get; set; }
        internal string Sid { get; set; }
        internal string Name { get; set; }
        internal string Help { get; set; }
        internal string CommandName { get; set; }
        internal string CommandHelp { get; set; }
        internal string CommandWarning { get; set; }
        internal string RootCommandSid { get; set; }
        internal sbyte IconKind { get; set; }
        internal string IconLabel { get; set; }
        internal string IconBmap { get; set; }
        internal byte Priority { get; set; }
        internal uint Layer { get; set; }
        internal sbyte Order { get; set; }
        internal sbyte Cycle { get; set; }
        internal byte Life { get; set; }
        internal sbyte Timing { get; set; }
        internal sbyte Target { get; set; }
        internal sbyte Frequency { get; set; }
        internal sbyte Stand { get; set; }
        internal sbyte Action { get; set; }
        internal string Condition { get; set; }
        internal string[] ActNames { get; set; }
        internal string[] ActOperations { get; set; }
        internal string[] ActValues { get; set; }
        internal sbyte AroundCenter { get; set; }
        internal sbyte AroundTarget { get; set; }
        internal string AroundCondition { get; set; }
        internal string AroundName { get; set; }
        internal string AroundOperation { get; set; }
        internal string AroundValue { get; set; }
        internal sbyte GiveTarget { get; set; }
        internal string GiveCondition { get; set; }
        internal string[] GiveSids { get; set; }
        internal string[] RemoveSids { get; set; }
        internal string[] SyncConditions { get; set; }
        internal string[] SyncSids { get; set; }
        internal string RebirthSid { get; set; }
        internal string EngageSid { get; set; }
        internal string[] ChangeSids { get; set; }
        internal string CooperationSkill { get; set; }
        internal string HorseSkill { get; set; }
        internal string CovertSkill { get; set; }
        internal string HeavySkill { get; set; }
        internal string FlySkill { get; set; }
        internal string MagicSkill { get; set; }
        internal string PranaSkill { get; set; }
        internal string DragonSkill { get; set; }
        internal string AttackRange { get; set; }
        internal string OverlapRange { get; set; }
        internal string OverlapTerrain { get; set; }
        internal string ZocRange { get; set; }
        internal sbyte ZocType { get; set; }
        internal sbyte Work { get; set; }
        internal string WorkOperation { get; set; }
        internal float WorkValue { get; set; }
        internal sbyte Power { get; set; }
        internal byte Rewarp { get; set; }
        internal byte Removable { get; set; }
        internal byte VisionCount { get; set; }
        internal byte Cost { get; set; }
        internal sbyte MoveSelf { get; set; }
        internal sbyte MoveTarget { get; set; }
        internal sbyte RangeTarget { get; set; }
        internal byte RangeI { get; set; }
        internal byte RangeO { get; set; }
        internal byte RangeAdd { get; set; }
        internal byte RangeExtend { get; set; }
        internal ulong Flag { get; set; }
        internal int Efficacy { get; set; }
        internal byte EfficacyValue { get; set; }
        internal int EfficacyIgnore { get; set; }
        internal int BadState { get; set; }
        internal int BadIgnore { get; set; }
        internal uint WeaponProhibit { get; set; }
        internal sbyte EnhanceLevel { get; set; }
        internal sbyte EnhanceValueHp { get; set; }
        internal sbyte EnhanceValueStr { get; set; }
        internal sbyte EnhanceValueTech { get; set; }
        internal sbyte EnhanceValueQuick { get; set; }
        internal sbyte EnhanceValueLuck { get; set; }
        internal sbyte EnhanceValueDef { get; set; }
        internal sbyte EnhanceValueMagic { get; set; }
        internal sbyte EnhanceValueMdef { get; set; }
        internal sbyte EnhanceValuePhys { get; set; }
        internal sbyte EnhanceValueMove { get; set; }
        internal sbyte WeaponLevelNone { get; set; }
        internal sbyte WeaponLevelSword { get; set; }
        internal sbyte WeaponLevelLance { get; set; }
        internal sbyte WeaponLevelAxe { get; set; }
        internal sbyte WeaponLevelBow { get; set; }
        internal sbyte WeaponLevelDagger { get; set; }
        internal sbyte WeaponLevelMagic { get; set; }
        internal sbyte WeaponLevelRod { get; set; }
        internal sbyte WeaponLevelFist { get; set; }
        internal sbyte WeaponLevelSpecial { get; set; }
        internal string[] EquipIids { get; set; }
        internal string Effect { get; set; }
        internal ushort InheritanceCost { get; set; }
        internal ushort InheritanceSort { get; set; }
    }
}
